### ISSUE TITLE
当队列满时，再添加可以自动覆盖最旧的吗？

### ISSUE THREAD

**Issue by bagualing** [hedzr/go-ringbuf#5]
跟着示例代码试了一下，当队列满时，再添加新元素，会直接返回队列已满的错误。
是否可以当队列满时，直接自动覆盖最旧的元素，而不是返回已满的错误呢？

**Comment by hedzr** [comment]
可以尝试做一份，今晚看看是否可行，太复杂的话就只好暂且挂起

**Comment by bagualing** [comment]
Nice job!
